exports.newWord = {
    wordList: ['RICK SANCHEZ', 'MORTY SMITH', 'SUMMER SMITH', 'JERRY SMITH', 'BETH SMITH', 'JESSICA', 'MR MEESEEKS', 'BIRDPERSON', 'SQUANCHY', 'UNITY', 'NOOB NOOB', 'KROMBOPULOS MICHAEL' ]
};